[package]
name = "softbuf"
version = "0.1.1"
edition = "2024"
description = "A software framebuffer library with drawing primitives and platform blitting"
license = "MIT"
authors = ["Patrick Reese (Retroboi64) <https://github.com/Retroboi64>"]
copyright = "Copyright (c) 2025 Patrick Reese (Retroboi64)"
repository = "https://github.com/Retroboi64/windowed"

[dependencies]
windowed = "0.2.0"
numix = "0.1.1"
raw-window-handle = "0.6"

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = { version = "0.13", features = ["allow-unsafe-code"] }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = [
    "wingdi",
    "winuser",
    "windef",
    "minwindef",
] }
